//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uSight_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public string license_plate { get; set; }
        public Nullable<int> times_searched { get; set; }
        public Nullable<System.TimeSpan> lastest_time { get; set; }
        public string searched_by { get; set; }
    }
}
