//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uSight_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchRecord
    {
        public System.DateTime Time { get; set; }
        public string PlateNumber { get; set; }
        public bool Stolen { get; set; }
        public string UserId { get; set; }
    }
}
