//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uSight_Web.Models
{
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
    
    public class SearchRecord
    {
        [Key]
        [Column(Order = 1)]
        public DateTime Time { get; set; }
        [Key]
        [Column(Order = 2)]
        public string PlateNumber { get; set; }
        public bool Stolen { get; set; } 
		public string UserId { get; set; }
    }
}
